//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class SampleEntityFramework : DbContext
{
    public SampleEntityFramework()
        : base("name=SampleEntityFramework")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Bancos> Bancos { get; set; }
    public DbSet<Capacidad> Capacidad { get; set; }
    public DbSet<Cliente> Cliente { get; set; }
    public DbSet<Comuna> Comuna { get; set; }
    public DbSet<Cotizacion> Cotizacion { get; set; }
    public DbSet<Empresa> Empresa { get; set; }
    public DbSet<Fletero> Fletero { get; set; }
    public DbSet<Licencias> Licencias { get; set; }
    public DbSet<MetodoPago> MetodoPago { get; set; }
    public DbSet<TipoCuenta> TipoCuenta { get; set; }
    public DbSet<TransferenciaBancaria> TransferenciaBancaria { get; set; }
    public DbSet<Vehiculo> Vehiculo { get; set; }
}
