//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Bancos
{
    public int idBancos { get; set; }
    public string nombre { get; set; }
}

public partial class Capacidad
{
    public int idCapacidad { get; set; }
    public Nullable<int> TaraKG { get; set; }
}

public partial class Cliente
{
    public int idCliente { get; set; }
    public string rut { get; set; }
    public string nombre { get; set; }
    public string apellidopaterno { get; set; }
    public string apellidomaterno { get; set; }
    public string email { get; set; }
}

public partial class Comuna
{
    public int idComuna { get; set; }
    public string nombre { get; set; }
    public string codigopostal { get; set; }
}

public partial class Cotizacion
{
    public int idCotizacion { get; set; }
    public string nombre { get; set; }
    public string apellidos { get; set; }
    public string rut { get; set; }
    public Nullable<long> telefono { get; set; }
    public string email { get; set; }
    public Nullable<System.DateTime> fechaInicio { get; set; }
    public Nullable<System.TimeSpan> horaInicio { get; set; }
    public string calleOrigen { get; set; }
    public string numeroOrigen { get; set; }
    public string comunaOrigen { get; set; }
    public string tipoviviendaOrigen { get; set; }
    public string tipoVehiculo { get; set; }
    public string nombreReceptor { get; set; }
    public string apellidoReceptor { get; set; }
    public string rutReceptor { get; set; }
    public Nullable<long> telefonoReceptor { get; set; }
    public string emailReceptor { get; set; }
    public Nullable<System.DateTime> fechaTermino { get; set; }
    public Nullable<System.TimeSpan> horaTermino { get; set; }
    public string calleDestino { get; set; }
    public string numeroDestino { get; set; }
    public string comunaDestino { get; set; }
    public string tipoviviendaDestino { get; set; }
    public Nullable<bool> servicioPioneta { get; set; }
    public Nullable<bool> servicioEmbalaje { get; set; }
    public Nullable<bool> servicioInventario { get; set; }
    public string estado { get; set; }
}

public partial class Empresa
{
    public int idEmpresa { get; set; }
    public string rut { get; set; }
    public string razonsocial { get; set; }
    public string email { get; set; }
    public string direccion { get; set; }
}

public partial class Fletero
{
    public int idFletero { get; set; }
    public string rut { get; set; }
    public string nombre { get; set; }
    public string apellidopaterno { get; set; }
    public string apellidomaterno { get; set; }
}

public partial class Licencias
{
    public int idLicencias { get; set; }
    public string clase { get; set; }
    public string descripcion { get; set; }
}

public partial class MetodoPago
{
    public int idMetodoPago { get; set; }
    public string nombre { get; set; }
    public string descripcion { get; set; }
}

public partial class TipoCuenta
{
    public int idTipoCuent { get; set; }
    public string nombre { get; set; }
    public string descripcion { get; set; }
}

public partial class TransferenciaBancaria
{
    public int idTransferenciaBancaria { get; set; }
    public string banco { get; set; }
    public string tipocuenta { get; set; }
    public string numerocuenta { get; set; }
    public string rut { get; set; }
    public string nombre { get; set; }
    public string apellidopaterno { get; set; }
    public string apellidomaterno { get; set; }
    public string email { get; set; }
    public Nullable<int> monto { get; set; }
}

public partial class Vehiculo
{
    public int idVehiculo { get; set; }
    public string marca { get; set; }
    public string modelo { get; set; }
    public Nullable<int> ano { get; set; }
    public string patente { get; set; }
    public string tipo { get; set; }
    public Nullable<System.DateTime> vencRevTec { get; set; }
}
