//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class mudanzaEntities : DbContext
{
    public mudanzaEntities()
        : base("name=mudanzaEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Bancos> Bancos { get; set; }
    public virtual DbSet<Capacidad> Capacidad { get; set; }
    public virtual DbSet<Cliente> Cliente { get; set; }
    public virtual DbSet<Comuna> Comuna { get; set; }
    public virtual DbSet<Cotizacion> Cotizacion { get; set; }
    public virtual DbSet<Fletero> Fletero { get; set; }
    public virtual DbSet<Licencias> Licencias { get; set; }
    public virtual DbSet<MetodoPago> MetodoPago { get; set; }
    public virtual DbSet<TipoCuenta> TipoCuenta { get; set; }
    public virtual DbSet<TransferenciaBancaria> TransferenciaBancaria { get; set; }
    public virtual DbSet<Vehiculo> Vehiculo { get; set; }
    public virtual DbSet<Empresa> Empresa { get; set; }
}
